# Generated by Django 4.0.2 on 2022-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('cashier', 'Cashier'), ('receptionis', 'Receptionist'), ('admin', 'Admin')], default='', max_length=100),
        ),
    ]
