# Generated by Django 4.0.2 on 2022-04-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0003_alter_profile_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_number', models.CharField(help_text='for existing patients', max_length=1000)),
                ('enviro_ID', models.CharField(max_length=20)),
                ('last_name', models.CharField(help_text='surname', max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('other_names', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('estimated_age', models.IntegerField(blank=True, help_text='Date of birth is approximate, leave blank if sure of date of birth', null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('religion', models.CharField(choices=[('CHRISTIANITY', 'CHRISTIANITY'), ('ISLAM', 'ISLAM'), ('TRADITIONALIST', 'TRADITIONALIST')], max_length=20)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorsed', 'Divorsed')], max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('state_of_residence', models.CharField(max_length=20)),
                ('residential_address', models.CharField(max_length=100)),
                ('state_of_origin', models.CharField(max_length=20)),
                ('LGA', models.CharField(max_length=30)),
                ('address_of_origin', models.CharField(max_length=100)),
                ('next_of_kin', models.CharField(max_length=40)),
                ('next_of_kin_relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Other', 'Other')], max_length=20)),
                ('next_of_kin_phone_number', models.CharField(max_length=11)),
                ('next_of_kin_address', models.CharField(max_length=100)),
            ],
        ),
    ]
